// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Prod.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240811084826_ModelValidation")]
    partial class ModelValidation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prod.Entity.ProductInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ProductInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 3,
                            Name = "Бумага/упак",
                            Price = 199.0
                        },
                        new
                        {
                            Id = 2,
                            Count = 10,
                            Name = "Ножницы/шт",
                            Price = 150.0
                        },
                        new
                        {
                            Id = 3,
                            Count = 7,
                            Name = "Карандаши/упак",
                            Price = 100.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
